{{- if and (.Values.rbac).enabled .Values.rbac.roles }}
{{- range .Values.rbac.roles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "application.name" $ }}-role-{{ .name }}
  namespace: {{ template "application.namespace" $ }}
  {{- with (mergeOverwrite $.Values.global.annotations $.Values.rbac.serviceAccount.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "artifactd.labels" $ | nindent 4 }}
    {{- with (mergeOverwrite $.Values.global.labels $.Values.rbac.serviceAccount.labels) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
{{ toYaml .rules | indent 2 }}
{{- end }}
{{- end }}